
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        group: dev
        namespace: 98c8e701-bdd7-4e17-a9d2-55ee3e051da8
  application:
    name: order-center

server:
  port: 8084
